# @format

name: Deploy NestJS to VPS

on:
    push:
        branches:
            - main # Запуск при пуше в main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      	export NVM_DIR=~/.nvm
                        source ~/.nvm/nvm.sh
                        nvm use 22
                        cd /var/www/server.top24.kz
                        git pull origin main
                        rm -rf node_modules package-lock.json dist
                        npm install
                        npm run build
                        pm2 restart server
